name: ci

on:
  push:
  pull_request:

jobs:
  sim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y verilator make g++ gcc-riscv64-unknown-elf

      - name: Build and run CPU test
        run: |
          make asm
          make c